exports.DB_BOOK_COLLECTION = 'books'; // Collection in DB
exports.DB_USER_COLLECTION = 'users'; // Collection in DB
exports.DB_NAME = 'bookshelf'; // Data base name
exports.PORT_HTTPS = 4420; // PORT FOR HTTPS
exports.PORT = 3202; // PORT FOR HTTP
exports.DB_FULL_PATH = `mongodb://localhost/${this.DB_NAME}`; // Path to connect db
exports.SECRET = 'BOOKSHELF'; // Secret used in JWT.
exports.TOKEN_TYPE = 'Bearer'; // Token
exports.CITIES = [/^Quito$/i, /^Medell[ií]n$/i, /^Cartagena$/i]; // Regrexp for cities
