exports.DB_BOOK_COLLECTION = 'books'; // Collection in DB
exports.DB_USER_COLLECTION = 'users'; // Collection in DB
exports.DB_NAME = 'bookshelf'; // Data base name
exports.PORT_HTTPS = 4420; // PORT FOR HTTPS
exports.PORT = 3202; // PORT FOR HTTP
exports.DB_FULL_PATH = `mongodb://localhost/${this.DB_NAME}`; // Path to connect db
exports.SECRET = '33d@eVaj3doo$#sqAswdBC$53'; // Secret used in JWT.
exports.TOKEN_TYPE = 'Bearer'; // Token
exports.CITIES = [/^[Qq]uito$/i, /^[Mm]edell[ií]n$/i, /^[Cc]artagena$/i]; // Regrexp for cities.
exports.PAGE_SIZE = 15; // How many book returns each request.
exports.TOKEN_EXPIRE_TIME = '60d'; // Live time for the JWT token.
exports.MAX_DAYS_LEND = 15;
